name: Deploy Python Lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #   LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME  }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Match your Lambda runtime

      - name: Install dependencies
        run: |
          mkdir -p src/python
          pip install -r src/requirements.txt -t src/python

      - name: Create deployment package
        run: |
          rm -f deployment.zip
          # Zip dependencies first
          cd src/python && zip -r ../../deployment.zip .
          # Then add your Lambda function
          cd src && zip -g ../deployment.zip lambda_function.py
          echo "Final zip contents:"
          unzip -l deployment.zip
          # Add other files if needed (configs, etc.)
          # zip -g ../deployment.zip *.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://deployment.zip